feat(bin): update scripts to function format

diff --git a/local/bin/x-backup-folder b/local/bin/x-backup-folder
--- a/local/bin/x-backup-folder
+++ b/local/bin/x-backup-folder
@@ -3,33 +3,84 @@
 # Backup a folder with a timestamp
 # Usage: x-backup-folder folder_to_backup [filename]
 # If filename is not provided, folder_to_backup will be used
+#
 # Example: x-backup-folder ~/Documents/MyFolder
 #
 # Copyright (c) 2022 Ismo Vuorinen. All Rights Reserved.
 # Licensed under the MIT license.
 
-DIRECTORY=$1
-FILENAME=$2
+set -euo pipefail
 
-if [ -z "${DIRECTORY}" ]; then
-  echo "DIRECTORY (first argument) is missing"
-  echo "Usage: $0 folder_to_backup"
-  exit
-fi
+# Enable verbosity with VERBOSE=1
+VERBOSE="${VERBOSE:-0}"
 
-if [ -z "${FILENAME}" ]; then
-  FILENAME=$DIRECTORY
-fi
+# Function to print usage information
+usage()
+{
+  echo "Usage: $0 folder_to_backup [filename]"
+  exit 1
+}
 
-FILENAME=$(
-  ${FILENAME} \
-    | tr '/' _ \
-    | iconv -t ascii//TRANSLIT \
-    | sed -r s/[^a-zA-Z0-9]+/_/g \
-    | sed -r s/^_+\|-+$//g
-)
+# Function to print messages if VERBOSE is enabled
+# $1 - message (string)
+msg()
+{
+  [[ "$VERBOSE" -eq 1 ]] && echo "$1"
+}
 
-TIMESTAMP=$(date "+%Y%m%d_%H%M%S")
-FILENAME_TIMESTAMP="${FILENAME}_${TIMESTAMP}"
+# Function to print error messages and exit
+# $1 - error message (string)
+msg_err()
+{
+  echo "(!) ERROR: $1" >&2
+  exit 1
+}
 
-tar cvzf "${FILENAME_TIMESTAMP}.tar.gz" "${DIRECTORY}/"
+# Function to sanitize the filename
+# $1 - filename (string)
+sanitize_filename()
+{
+  local filename=$1
+  echo "$filename" | tr '/' '_' | iconv -t ascii//TRANSLIT | sed -r 's/[^a-zA-Z0-9]+/_/g' | sed -r 's/^_+|_+$//g'
+}
+
+# Function to backup the directory
+# $1 - directory to backup (string)
+# $2 - filename prefix (string)
+backup_directory()
+{
+  local directory=$1
+  local filename=$2
+
+  local sanitized_filename
+  sanitized_filename=$(sanitize_filename "$filename")
+
+  local timestamp
+  timestamp=$(date "+%Y%m%d_%H%M%S")
+  local filename_timestamp="${sanitized_filename}_${timestamp}"
+
+  msg "Backing up directory '$directory' to '${filename_timestamp}.tar.gz'"
+
+  tar cvzf "${filename_timestamp}.tar.gz" "${directory}/"
+
+  msg "Backup completed and saved to '${filename_timestamp}.tar.gz'"
+}
+
+# Main function
+main()
+{
+  if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
+    usage
+  fi
+
+  local directory=$1
+  local filename=${2:-$directory}
+
+  if [ -z "$directory" ]; then
+    msg_err "DIRECTORY (first argument) is missing"
+  fi
+
+  backup_directory "$directory" "$filename"
+}
+
+main "$@"
diff --git a/local/bin/x-gh-get-latest-release-targz b/local/bin/x-gh-get-latest-release-targz
--- a/local/bin/x-gh-get-latest-release-targz
+++ b/local/bin/x-gh-get-latest-release-targz
@@ -1,17 +1,102 @@
 #!/usr/bin/env bash
+#
+# Fetch the latest release version of a GitHub repository in tar.gz format (e.g. v1.0.0.tar.gz)
+# Usage: x-gh-get-latest-release-targ <repo> [--get]
+# Author: Ismo Vuorinen <https://github.com/ivuorinen> 2024
 
-REPO=$1
+set -euo pipefail
 
-if [ -z "$REPO" ]; then
-  echo "Usage: $0 <repo> (e.g. ivuorinen/dotfiles)"
+# Enable verbosity with VERBOSE=1
+VERBOSE="${VERBOSE:-0}"
+
+# Function to print usage information
+usage()
+{
+  echo "Usage: $0 <github repo> [--get] (e.g. ivuorinen/dotfiles)"
+  echo "  --get: Download and extract the tarball"
   exit 1
-fi
+}
 
-LOCATION=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" \
-  | sed -Ene '/^[[:blank:]]+"tarball_url":[[:blank:]]"(https:[^"]+)",/s//\1/p')
+# Function to print messages if VERBOSE is enabled
+# $1 - message (string)
+msg()
+{
+  [[ "$VERBOSE" -eq 1 ]] && echo "$1"
+  return 0
+}
 
-echo "Downloading and extracting from: $LOCATION"
+# Function to fetch the tarball URL of the latest release from GitHub
+# $1 - GitHub repository (string)
+get_latest_tarball_url()
+{
+  local repo=$1
 
-curl --location --silent "$LOCATION" | tar --extract --gzip --file=-
+  local tarball_url
+  tarball_url=$(curl -s "https://api.github.com/repos/${repo}/releases/latest" \
+    | sed -Ene '/^[[:blank:]]+"tarball_url":[[:blank:]]"(https:[^"]+)",/s//\1/p')
+
+  if [ -z "$tarball_url" ]; then
+    echo "(!) Failed to fetch the tarball URL for repository: $repo"
+    exit 1
+  fi
+
+  echo "$tarball_url"
+  return 0
+}
+
+# Function to download and extract the tarball
+# $1 - tarball URL (string)
+download_and_extract()
+{
+  local url="$1"
+
+  msg "Downloading and extracting from: $url"
+  curl --location --silent "$url" | tar --extract --gzip --file=- || {
+    echo "(!) Failed to download or extract the tarball."
+    exit 1
+  }
+
+  return 0
+}
+
+# Main function
+main()
+{
+  if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
+    usage
+  fi
+
+  local repo=$1
+  local get_tarball=false
+
+  if [ "$#" -eq 2 ]; then
+    # Check if the first or second argument is --get
+    if [ "$1" == "--get" ] || [ "$2" == "--get" ]; then
+      get_tarball=true
+    else
+      usage
+    fi
+  fi
+
+  # Check if the first argument is --get
+  if [ "$1" == "--get" ]; then
+    repo="$2"
+  fi
+
+  msg "Fetching the tarball URL for the latest release of repository: $repo"
+
+  local location
+  location=$(get_latest_tarball_url "$repo")
+
+  if $get_tarball; then
+    download_and_extract "$location"
+  else
+    echo "$location"
+  fi
+
+  return 0
+}
+
+main "$@"
 
 # vim: set ts=2 sw=2 ft=sh et:
diff --git a/local/bin/x-thumbgen b/local/bin/x-thumbgen
--- a/local/bin/x-thumbgen
+++ b/local/bin/x-thumbgen
@@ -1,39 +1,69 @@
 #!/usr/bin/env bash
-# Generate thumbnails using magick
+# Generate thumbnails using ImageMagick (magick)
 # https://imagemagick.org/script/download.php
 #
-# Defaults to current directory creating thumbs with 1000x1000
-# images with 200px white borders around the original image.
+# Defaults to current directory creating thumbnails with 1000x1000
+# dimensions and 200px white borders around the original image.
 #
 # Defaults can be overridden with ENV variables like this:
 # $ THMB_BACKGROUND=black x-thumbgen ~/images/
 #
 # Created by: Ismo Vuorinen <https://github.com/ivuorinen> 2015
 
-: "${THMB_SOURCE:=$1}"
+set -euo pipefail
+
+# Default values
+: "${THMB_SOURCE:=${1:-}}"
 : "${THMB_BACKGROUND:=white}"
 : "${THMB_RESIZE:=800x800}"
 : "${THMB_EXTENT:=1000x1000}"
 
-[ $# -eq 0 ] && {
+# Print usage information
+usage()
+{
   echo "Usage: $0 /full/path/to/image/folder"
   exit 1
 }
 
-if [ "$THMB_SOURCE" == "" ] || [ ! -d "$THMB_SOURCE" ]; then
-  THMB_SOURCE=$(pwd)
-fi
+# Check if ImageMagick is installed
+check_magick_installed()
+{
+  if ! command -v magick &> /dev/null; then
+    echo "magick not found in PATH, https://imagemagick.org/script/download.php"
+    exit 1
+  fi
+}
 
-if command -v magick &> /dev/null; then
+# Generate thumbnails
+generate_thumbnails()
+{
+  local source=$1
 
   magick \
-    "$THMB_SOURCE/*" \
+    "${source}/*" \
     -resize "$THMB_RESIZE" \
     -background "$THMB_BACKGROUND" \
     -gravity center \
     -extent "$THMB_EXTENT" \
     -set filename:fname '%t_thumb.%e' +adjoin '%[filename:fname]'
+}
 
-else
-  echo "magick not found in PATH, https://imagemagick.org/script/download.php"
-fi
+# Main function
+main()
+{
+  # Validate input
+  if [ -z "$THMB_SOURCE" ]; then
+    usage
+  fi
+
+  # Check if the source directory is valid
+  if [ ! -d "$THMB_SOURCE" ]; then
+    echo "Invalid directory: $THMB_SOURCE"
+    exit 1
+  fi
+
+  check_magick_installed
+  generate_thumbnails "$THMB_SOURCE"
+}
+
+main "$@"
