Fix shfmt command and formatted files

diff --git a/local/bin/x-ssl-expiry-date b/local/bin/x-ssl-expiry-date
--- a/local/bin/x-ssl-expiry-date
+++ b/local/bin/x-ssl-expiry-date
@@ -20,9 +20,10 @@
 #
 #  Simple function to show usage information, and exit.
 #
-usage() {
-    echo "Usage: $0 [-d] [-p 443] domain1.org domain2.com .. domainN"
-    exit 0
+usage()
+{
+  echo "Usage: $0 [-d] [-p 443] domain1.org domain2.com .. domainN"
+  exit 0
 }
 
 #
@@ -35,19 +36,19 @@ port=443
 #  Parse the argument(s) - i.e. look for "-d" / "-p 443".
 #
 while getopts "h?dp:" opt; do
-    case $opt in
-        h)
-            usage
-            ;;
-        \?)
-            usage
-            ;;
-        d)
-            days=1
-            ;;
-        p)
-            port=$OPTARG
-            ;;
+  case $opt in
+    h)
+      usage
+      ;;
+    \?)
+      usage
+      ;;
+    d)
+      days=1
+      ;;
+    p)
+      port=$OPTARG
+      ;;
   esac
 done
 shift $((OPTIND - 1))
@@ -56,7 +57,7 @@ shift $((OPTIND - 1))
 #  Ensure we have some arguments
 #
 if [ "$#" = "0" ]; then
-    usage
+  usage
 fi
 
 #
@@ -64,70 +65,70 @@ fi
 #
 for name in "$@"; do
 
-    #
-    #  Make a temporary file
-    #
-    # Test if we have BSD or GNU version of mktemp
-    if ( strings "$(which mktemp)" | grep -q GNU); then
-        # We have the GNU version
-        tmp=$(mktemp)
+  #
+  #  Make a temporary file
+  #
+  # Test if we have BSD or GNU version of mktemp
+  if (strings "$(which mktemp)" | grep -q GNU); then
+    # We have the GNU version
+    tmp=$(mktemp)
   else
-        # We have the BSD version
-        tmp=$(mktemp -t tmp)
+    # We have the BSD version
+    tmp=$(mktemp -t tmp)
   fi
 
-    #
-    #  Download the certificate
-    #
-    if ( ! echo "" | openssl s_client -connect $name:$port > $tmp 2> /dev/null); then
-        echo "Failed to get cert from https://$name:$port/"
-        exit 3
+  #
+  #  Download the certificate
+  #
+  if (! echo "" | openssl s_client -connect $name:$port > $tmp 2> /dev/null); then
+    echo "Failed to get cert from https://$name:$port/"
+    exit 3
   fi
 
-    #
-    #  Get the expiry date
-    #
-    date=$(openssl x509 -in "$tmp" -noout -enddate | awk -F= '{print $2}')
+  #
+  #  Get the expiry date
+  #
+  date=$(openssl x509 -in "$tmp" -noout -enddate | awk -F= '{print $2}')
 
-    #
-    #  Remove the temporary file
-    #
-    rm -f "$tmp"
+  #
+  #  Remove the temporary file
+  #
+  rm -f "$tmp"
 
-    #
-    #  Convert the expiry date + todays date to seconds-past epoch
-    #
-    # Check if we have the BSD or the GNU version of date
-    if (strings "$(which date)" | grep -q GNU); then
-        # We have GNU this is easy
-        then=$(date --date "$date" +%s)
+  #
+  #  Convert the expiry date + todays date to seconds-past epoch
+  #
+  # Check if we have the BSD or the GNU version of date
+  if (strings "$(which date)" | grep -q GNU); then
+    # We have GNU this is easy
+    then=$(date --date "$date" +%s)
   else
-        # We have BSD now it is getting complicated
-        year=$(echo "$date" | awk '{print $4}')
-        month=$(echo "$date" | awk '{print $1}')
-        day=$(echo "$date" | awk '{print $2}')
-        hour=$(echo "$date" | awk '{print $3}' | awk -F: '{print $1}')
-        minute=$(echo "$date" | awk '{print $3}' | awk -F: '{print $2}')
-        second=$(echo "$date" | awk '{print $3}' | awk -F: '{print $3}')
-        then=$(date -v${year}y -v${month} -v${day}d -v${hour}H -v${minute}M -v${second}S -u +%s)
+    # We have BSD now it is getting complicated
+    year=$(echo "$date" | awk '{print $4}')
+    month=$(echo "$date" | awk '{print $1}')
+    day=$(echo "$date" | awk '{print $2}')
+    hour=$(echo "$date" | awk '{print $3}' | awk -F: '{print $1}')
+    minute=$(echo "$date" | awk '{print $3}' | awk -F: '{print $2}')
+    second=$(echo "$date" | awk '{print $3}' | awk -F: '{print $3}')
+    then=$(date -v${year}y -v${month} -v${day}d -v${hour}H -v${minute}M -v${second}S -u +%s)
   fi
 
-    now=$(date +%s)
+  now=$(date +%s)
 
-    #
-    #  Day diff
-    #
-    diff=$(("$then" - "$now"))
-    diff=$($diff / 86400)
+  #
+  #  Day diff
+  #
+  diff=$(("$then" - "$now"))
+  diff=$($diff / 86400)
 
-    #
-    #  All done
-    #
-    if [ "$days" = "1" ]; then
-        echo "${name}: ${diff}"
+  #
+  #  All done
+  #
+  if [ "$days" = "1" ]; then
+    echo "${name}: ${diff}"
   else
-        echo "$name"
-        echo "    Expires: ${date}"
-        echo "    Days: ${diff}"
+    echo "$name"
+    echo "    Expires: ${date}"
+    echo "    Days: ${diff}"
   fi
 done
